export const PROFILE_FORM_ACTIONS = {
  SET_TEXT_FIELD: 'SET_TEXT_FIELD',
  SET_YEARS_EXPERIENCE: 'SET_YEARS_EXPERIENCE',
  INCREMENT_YEARS_EXPERIENCE: 'INCREMENT_YEARS_EXPERIENCE',
  DECREMENT_YEARS_EXPERIENCE: 'DECREMENT_YEARS_EXPERIENCE',
  SET_CHIP_FIELD: 'SET_CHIP_FIELD',
  RESET: 'RESET',
} as const;
