import { StyleSheet } from 'react-native';

export const analysisDetailStyles = StyleSheet.create({
  content: {
    gap: 18,
    paddingBottom: 34,
    paddingTop: 18,
  },
  header: {
    gap: 10,
    marginBottom: 4,
  },
  eyebrow: {
    color: '#8fb8ff',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  title: {
    color: '#f8fafc',
    fontSize: 31,
    fontWeight: '800',
    lineHeight: 38,
  },
  subtitle: {
    color: '#cbd5e1',
    fontSize: 16,
    lineHeight: 24,
  },
  scoreCard: {
    alignItems: 'center',
    backgroundColor: '#17212b',
    borderColor: '#263442',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 18,
  },
  scoreLabel: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  scoreValue: {
    color: '#f8fafc',
    fontSize: 48,
    fontWeight: '900',
    lineHeight: 54,
  },
  statusBadge: {
    backgroundColor: '#223246',
    borderColor: '#334965',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  statusText: {
    color: '#dbeafe',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  statGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    backgroundColor: '#17212b',
    borderColor: '#263442',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    minHeight: 82,
    padding: 14,
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  statValue: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  sectionCard: {
    backgroundColor: '#17212b',
    borderColor: '#263442',
    borderRadius: 10,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  sectionLabel: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '800',
  },
  copyButton: {
    backgroundColor: '#223246',
    borderColor: '#334965',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  copyButtonPressed: {
    opacity: 0.75,
  },
  copyButtonDisabled: {
    opacity: 0.45,
  },
  copyButtonText: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  sectionText: {
    color: '#f8fafc',
    fontSize: 15,
    lineHeight: 22,
  },
  stateCard: {
    alignItems: 'center',
    backgroundColor: '#17212b',
    borderColor: '#263442',
    borderRadius: 10,
    borderWidth: 1,
    gap: 8,
    padding: 18,
  },
  stateTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '800',
  },
  stateText: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
});
